title: Lime
email: limegit@gmail.com

tagline: Cuma Web Statis
description: >
        Website statis, pembasahan pada artikel-artikel disini akan sangat jarang.

url: "https://lime.web.id"

iconURL: /assets/icon-lime.png
theme: jekyll-theme-leaf

destination: docs

# for a clean URL
permalink: /:year/:month/:title.html

social:
  twitter: jekyllrb
  github: limekecut

plugins:
 - jekyll-feed
 - jekyll-seo-tag

jekyll_admin:
  hidden_links:
    - datafiles

### comments & analytics
hyvor_talk_website_id: 2408
google_analytics: UA-NNNNNNNN-N

include:
  - CNAME

exclude:
  - deploy.sh
  - live.sh
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-leaf.gemspec
  - LICENSE.txt
  - README.md
